<a href="https://colab.research.google.com/github/Armina101/Postpartum-depression-prediction-model/blob/main/postpartum_depression_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Data Pre-processing**

## **Importing all needed libraries**

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## **Read Dataset**

In [ ]:
df=pd.read_csv('https://raw.githubusercontent.com/Armina101/Postpartum-depression-prediction-model/refs/heads/main/THP_clean.csv')

In [ ]:
df.head()

,newid,interviewer,uc,grandmother,employed_mo,income_mo,income_hh,genhealth,edu_mo,edu_fa,...,infantdev_1y,infantdev_1y_f,parentinputs_infancy,parentinputs_infancy_f,infantdev,infantdev_f,motherfinancial_7y,motherfinancial_7y_f,socialsupport,socialsupport_f
0,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,7.319728,...,-1.550027,-0.914190,0.845854,0.341055,-1.155602,-0.975243,NaN,NaN,1.496326,NaN
1,226.0,1.0,1,No,No,0.0,60.0,Very good,0.0,8.000000,...,0.919651,0.044339,2.737210,0.550107,0.587643,0.244921,-0.064279,-0.346433,2.569177,1.731267
2,222.0,6.0,1,Yes,No,0.0,200.0,Moderate,7.0,9.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,-0.521870,-0.295887,1.275779,NaN
3,3.0,1.0,1,No,No,0.0,150.0,Good,0.0,5.000000,...,1.589225,0.971888,0.634669,0.429139,0.326545,0.626777,0.521984,-0.163072,-0.521288,-0.880748
4,217.0,3.0,1,No,No,0.0,250.0,0,5.0,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,0.521984,-0.163072,1.275779,NaN

In [14]:
df.tail()

,newid,interviewer,uc,grandmother,employed_mo,income_mo,income_hh,genhealth,edu_mo,edu_fa,...,infantdev_1y,infantdev_1y_f,parentinputs_infancy,parentinputs_infancy_f,infantdev,infantdev_f,motherfinancial_7y,motherfinancial_7y_f,socialsupport,socialsupport_f
1198,546.0,5.0,40,Yes,No,0.0,150.0,Very good,0.0,10.000000,...,-0.213161,-0.325892,0.746556,0.541312,0.176705,-0.694231,-0.064279,-0.346433,0.204220,-0.035893
1199,NaN,NaN,40,NaN,NaN,NaN,NaN,NaN,NaN,7.319728,...,-0.315063,-0.402695,0.425044,NaN,0.903029,0.132893,NaN,NaN,-0.025040,NaN
1200,594.0,5.0,40,Yes,No,0.0,80.0,Moderate,4.0,7.000000,...,1.145054,0.341715,0.746556,0.541312,1.455266,0.502727,0.521984,-0.163072,0.747689,0.313829
1201,568.0,5.0,40,No,Yes,NaN,NaN,Good,5.0,8.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,0.449251,NaN,-0.380235,NaN
1202,NaN,NaN,40,NaN,NaN,NaN,NaN,NaN,NaN,7.319728,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## **Sanity check of data**

In [13]:
df.shape

(1203, 394)

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1203 entries, 0 to 1202
Columns: 394 entries, newid to socialsupport_f
dtypes: float64(366), int64(11), object(17)
memory usage: 3.6+ MB

### **Finding Duplicate Values**

In [18]:
df.duplicated().sum()

np.int64(0)

### **Identifying Garbage Values**

In [19]:
for i in df.select_dtypes(include='object').columns:
  print(df[i].value_counts())
  print("***"*10)

grandmother
No     538
Yes    347
Name: count, dtype: int64
******************************
employed_mo
No     781
Yes    104
Name: count, dtype: int64
******************************
genhealth
Good         364
Moderate     251
Very good    184
0             70
Bad           16
Name: count, dtype: int64
******************************
ideal_no_kids
4     267
3     262
2     237
5      58
6      18
.d     11
7      10
1       9
8       8
0       4
Name: count, dtype: int64
******************************
mo_185
Yes    558
No     301
Name: count, dtype: int64
******************************
mo_358
not played at all    602
.25                  105
once or twice        102
.5                    56
.75                   20
Name: count, dtype: int64
******************************
mo_360
Yes    517
No     368
Name: count, dtype: int64
******************************
ch_27
Yes    704
No     170
Name: count, dtype: int64
******************************
ch_28
Yes    744
No     130
Name: count, dtype: int64
******************************
ch_29
No     476
Yes    398
Name: count, dtype: int64
******************************
ch_30
No     507
Yes    367
Name: count, dtype: int64
******************************
ch_31
Yes    793
No      81
Name: count, dtype: int64
******************************
ch_32
Yes    814
No      60
Name: count, dtype: int64
******************************
ch_33
Yes    857
No      17
Name: count, dtype: int64
******************************
ch_34
No     581
Yes    293
Name: count, dtype: int64
******************************
ch_35
No     598
Yes    276
Name: count, dtype: int64
******************************
ch_36
Yes    431
No     419
Name: count, dtype: int64
******************************

### **Fixing Garbage Values**

In [22]:
df['genhealth'] = df['genhealth'].replace("0", np.nan)
df['ideal_no_kids'] = df['ideal_no_kids'].replace("0", np.nan)
df['ideal_no_kids'] = pd.to_numeric(df['ideal_no_kids'], errors='coerce')

In [25]:
mapping = {
    "not played at all": 0.0,
    "once or twice": 0.25
}
df["mo_358"] = df["mo_358"].replace(mapping)
df["mo_358"] = pd.to_numeric(df["mo_358"], errors="coerce")

### **Fixing Missing Values**

In [16]:
df.isnull().sum()

newid                   318
interviewer             318
uc                        0
grandmother             318
employed_mo             318
                       ...
infantdev_f             500
motherfinancial_7y      318
motherfinancial_7y_f    353
socialsupport            83
socialsupport_f         619
Length: 394, dtype: int64

In [17]:
df.isnull().sum()/df.shape[0]*100

newid                   26.433915
interviewer             26.433915
uc                       0.000000
grandmother             26.433915
employed_mo             26.433915
                          ...
infantdev_f             41.562760
motherfinancial_7y      26.433915
motherfinancial_7y_f    29.343308
socialsupport            6.899418
socialsupport_f         51.454697
Length: 394, dtype: float64